guardian/interactive-component-library

src/lib/styles/foundation/euPartyColors.scss
src/lib/styles/main.scss

For components that need to recognise the EU elections - adding the party groupings for the EU parliament and their associated colors. 
eg:

COLORS: add EU party colors

---

src/lib/components/molecules/table/index.jsx
src/lib/components/molecules/table/style.module.scss
src/lib/components/molecules/table/table.stories.jsx

In some designs, we hide the header of a table. This adds an option so the user can choose not to show the header
But we don't want to remove the header entirely - ie: by using `display: none;` - because column widths are calculated by the table header cells. 
Instead we apply a class that uses `visibility: hidden;` and various other CSS properties to keep the effects of the table header but to hide it from view. 
QUESTION: should i add an option to make the first row bold? or should this be achievable thru the style prop? 
WITH HEADER 
WITHOUT HEADER 
- works less well for sortable tables - but by definition these should have a header - otherwise they are not sortable

Table Molecule: option to hide header

---

src/lib/components/molecules/topline-result/topline-result.stories.jsx
src/lib/components/molecules/topline-result/topline-result.stories.module.scss

Small PR just adding to a story. 
Documents how to right-align the topline result component so it can look like this:

Topline Result - add a style prop to stories

---

src/lib/styles/foundation/partyColors.scss

adds stop colour for NOC

---

src/lib/components/molecules/map/layers/CompositionBorders.jsx
src/lib/components/molecules/map/layers/Line.jsx
src/lib/components/molecules/map/layers/Point.jsx
src/lib/components/molecules/map/layers/Polygon.jsx
src/lib/components/molecules/map/layers/compositionBorders.module.scss

set map colour defaults to null and add style file for composition border

---

src/lib/components/organisms/ticker/index.jsx

Ticker scrolling cleanup

---

src/lib/components/particles/change-bar/index.jsx
src/lib/components/particles/change-bar/style.module.scss

Add zero line to changebar

---

src/lib/components/particles/stacked-bar/index.jsx

replace alignment baseline with dominant baseine

---

src/lib/styles/helpers/mergeStyles.js
src/lib/styles/helpers/mergeStyles.test.js

* Fix for: https://trello.com/c/CGr5SPa8/53-style-merge-function-in-the-component-library-does-not-merge-nested-objects
* Also adds tests for this mergeStyles function

Fix merging nested style objects

---

src/lib/components/molecules/page-section/index.jsx
src/lib/components/molecules/page-section/page-section.stories.jsx

Fixes for: https://trello.com/c/94jEbrB1/263-section-component-if-we-edited-the-section-blurbs-to-be-bigger-they-would-spill-over-vertically-eg-regional-mayors

Set min height based on header content

---

src/lib/components/molecules/dropdown/index.jsx

It fixes the color for group headings on dark mode

Dropdown group headings fix

---

src/lib/components/particles/stacked-bar/index.jsx
src/lib/styles/foundation/partyColors.scss

Kinda hacky tweaks to the StackedBar component to allow for UK party colors to have a secondary more faded colour AND also to have a stroke color set by their abbreviation. 
sorry about the code the election is close

Stacked Bar: allow for faded fill (uk party colors) and for a rectangle border 

---

src/lib/components/molecules/table/table.stories.jsx
src/lib/components/molecules/table/useTable.jsx

Remove use of `Array.prototype.toSorted()` function because it is not supported by older browsers

Remove use of toSorted function

---

src/lib/components/organisms/ticker/index.jsx

On mobile iOS (safari and app) the button control panel for the ticker got hidden too easily - anytime the panel was expanded.
This changes the check at mobile width to prevent this happening. Only when there two or fewer items in the ticker will the buttons disappear. The height check was producing the wrong effect and got triggered too easily.
BUG:  - show fewer button hidden at bottom 
WORKING: 
https://github.com/guardian/interactive-component-library/assets/10324129/9e6d8d2c-4ce1-4798-8f62-4ca62eb85c83
NB: lots of linting changes here

Ticker Bug: change hidebutton function to fix mobile bug

---

src/lib/components/particles/waffle/index.jsx

Request from user feedback, is that the waffle should be less jumpy, and therefore only trigger the opacity changes `onClick` not `onMouseOver`.
- Adding an onClick event to the waffle
- Adding default empty functions for the two functions, to avoid giving an error if the user doesn't want to define these.
Formatting changes make these changes look bigger than they are

Waffle component: add onclick event

---

src/lib/components/molecules/canvas-map/lib/renderers/FeatureRenderer.js

When drawing the map, `window.devicePixelRatio` wasn't properly taken into account, resulting in borders appearing visually different on screens with different resolutions.

Fix subtle stroke width bug in Map component

---

src/lib/components/molecules/modal/style.module.css

adding an `exitActive` state to make the Modal's exit from the page smooth and more of a slide-out. 
Removing the `exit` class as this overlaps with `exitDone` and  and caused a few glitches with `exitActive`. 
CSSTransition Classes from here: https://www.npmjs.com/package/preact-transitioning
OLD - modal abruptly disappears when you click X
https://github.com/guardian/interactive-component-library/assets/10324129/2f13efea-70d0-4931-928f-cc823bd987c4
NEW - modal slides out when you click X 
https://github.com/guardian/interactive-component-library/assets/10324129/635eb3ba-5533-4489-8eed-7739a3574786

Modal: animate exit active state - for smoother exit

---

src/lib/components/molecules/canvas-map/Map.jsx
src/lib/components/molecules/svg-map/index.jsx
src/lib/components/molecules/table/index.jsx
src/lib/components/organisms/coalitions-tracker/index.jsx

Implements some SEO recommendations from this card https://trello.com/c/w14Q54ax/415-seo-based-tweaks
Some extra improvements are made [here](https://github.com/guardian/interactive-uk-ge-2024/pull/84), on the uk page.
See commits for more details

Various SEO improvements

---

src/lib/components/molecules/modal/style.module.css

A bug with the party tooltips meant that clicks on the blurred background area outside the tooltip failed to register

Modal bug: clicks on transition container failing to register 

---

src/lib/components/molecules/search-input/index.jsx
src/lib/components/molecules/search-input/style.module.css

This allows showing search errors as disabled suggestions:
Also adds support for pressing 'Escape' key to remove focus from search input.

Add option for disabled suggestions

---

src/lib/components/organisms/ticker/index.jsx

I don't know why this check was okay before, but now has started causing a problem on desktop... but it has. The show more button was hidden on desktop too frequently. 
Have amended the show more button to show any time there are 3 or more results. 
The 2nd time i've amended this
https://github.com/guardian/interactive-component-library/pull/152

Ticker: the show more button bug returns

---

src/lib/components/organisms/ticker/index.jsx
src/lib/components/organisms/ticker/style.module.scss

At mobile: the show fewer button scrolls you up to the top of the ticker, so the user feels less disoriented
At desktop: a bug where the scroll to the right button would grey out, preventing you from seeing the last few items has been fixed. Adding the dependency `childArray` seemed to improve this.

Ticker: fixes

---

src/lib/components/organisms/ticker/index.jsx

At desktop - the right arrow button was staying ennabled for too long. It should disable sooner - turned out minus 2 makes it behave correctly 
NB: right arrow now disabled

Ticker button: fix disabled state

---

src/lib/components/molecules/svg-map/hooks/useThrowIfNonLayerChildren.js

`useEffect` should be imported from "preact/hooks". 
Fix for a small bug causing problems when linking the library to a client repo

Fix: import from preact/hooks bug

---

src/lib/styles/foundation/usPartyColors.scss

Adds `undeclared` to this file which seems to fix a dark mode problem in the US election repo 
undeclared section now a darker grey that fades more into the background: 
Note:
I don't fully understand why the us repo can't pick up eg `--fill-color--undeclared` from [ukColors](https://github.com/guardian/interactive-component-library/blob/main/src/lib/styles/foundation/ukPartyColors.scss#L321) but 🤷 ?

Colors: add undeclared to US color palette 

---

package.json
pnpm-lock.yaml

This PR undoes the damage I did with one of my first commits (12e9cdbf109ecd7fd71ead57cc0083be32923fe6), where I completely wiped the old pnpm lockfile and replaced it with a newer lockfile version (we went from `lockfileVersion: '6.0'` to `lockfileVersion: '9.0'`.
This happened because I'd installed pnpm version 9, not version 8.4 as our package.json's `packageManager` config says!
I've added a `pnpm` setting to our package.json's `engines` object so that npm/pnpm will fail and shout, to stop this from happenign again.
I've sifted through the lockfile to check that none of our dependency versions have been changed. It looks as though they haven't, or at least, they all follow the upgrade policy in our package.json.

Fix pnpm lockfile version

---

jsconfig.json
package.json
src/lib/components/molecules/canvas-map/Map.jsx
src/lib/components/molecules/canvas-map/context/MapContext.jsx
src/lib/components/molecules/canvas-map/lib/Map.js
src/lib/components/molecules/canvas-map/lib/layers/TextLayer.js
src/lib/components/molecules/canvas-map/lib/layers/VectorLayer.js
src/lib/components/molecules/canvas-map/lib/layers/index.js
src/lib/components/molecules/canvas-map/map.stories.jsx
src/lib/components/molecules/canvas-map/sample-data/uk-cities.json

This PR adds a React/JSX wrapper around the canvas map's layer components (`VectorLayer` and `TextLayer`).
Essentially, this means that we can replace this...
```jsx
<Map {...args}>
{{
controls: [],
layers: [outlineLayer, constituenciesLayer],
}}
</Map>
```
with this...
```jsx
<Map {...args}>
<VectorLayer.Component
features={new GeoJSON().readFeaturesFromObject(outline)}
style={fillStyle}
/>
<VectorLayer.Component
features={new GeoJSON().readFeaturesFromObject(constituencies)}
style={(feature) => {  /* ... */ }}
/>
</Map>
```
Much more React-y!
These components were added as a static method on the layer classes themselves, so that we can still create them using the `with` method (i.e. use these layers outside of React).
This change addresses the warnings that appear by our import …

Canvas map layer components

---

src/lib/components/particles/circle-icon/circle-icon.stories.jsx
src/lib/components/particles/circle-icon/index.jsx
src/lib/components/particles/gradient-icon/style.module.css

CircleIcon
- adding a diameter property (defaulting to 11) so that the size of this circle can be adjusted by the client
- allowed some adjustment space in viewport and svg height + width properties
- changed this from a rect to a circle element. This seemed more semantic to me. Unless I'm missing some good reason why it was a rect? 
GradientIcon
- some CSS that helped with positioning was invalid, so fixed this. It makes it sit better in the line. 
looks like:

CircleIcon: add diameter prop

---

.github/workflows/publish-package.yml

This PR makes sure that our "Publish package to NPM" action doesn't corrupt the package.json, by removing the newline at the end of file.
Doing so makes Prettier confused and causes the lint action to stall, as can be seen in this PR: https://github.com/guardian/interactive-component-library/pull/231.

Fix version bump action's changes to package.json

---

.github/workflows/ci.yml

[As it turns out, our workflows simply cannot be triggered for PR branches created by bots.](https://github.com/peter-evans/create-pull-request/issues/48)
There are solutions that involve creating a new user for bot PRs such as these, but it's easier to just assume that these PR branches don't need to be linted, which they really don't!

Ignore auto-version-* branches in lint workflow

---

src/lib/styles/foundation/usPartyColors.scss

* small mistake in color declaration

US colors: fix typo in color var

---

.github/workflows/pr-npm-comment.yml

It's always tricky to remember how to form these `npm i ...` incantations for Git branches, this comment aims to help us quickly try out component library changes in branches in other projects.
See below!

Add comment to PRs with `npm i` command

---

src/lib/components/molecules/search-input/index.jsx

This PR adds the `autocomplete="off"` attribute to the SearchInput's `<input>`, so that the native browser autocomplete UI doesn't get in the way of the component's, as shown below.

Disable browser autocomplete for SearchInput

---

package.json
pnpm-lock.yaml
src/lib/components/molecules/canvas-map/Map.jsx
src/lib/components/molecules/canvas-map/index.js
src/lib/components/molecules/canvas-map/lib/Feature.js
src/lib/components/molecules/canvas-map/lib/FeatureCollection.js
src/lib/components/molecules/canvas-map/lib/Map.js
src/lib/components/molecules/canvas-map/lib/View.js
src/lib/components/molecules/canvas-map/lib/formats/GeoJSON.js
src/lib/components/molecules/canvas-map/lib/geometry/Geometry.js
src/lib/components/molecules/canvas-map/lib/layers/VectorLayer.js
src/lib/components/molecules/canvas-map/lib/projection/index.js
src/lib/components/molecules/canvas-map/lib/sources/VectorSource.js
src/lib/components/molecules/canvas-map/lib/styles/Text.js
src/lib/components/molecules/canvas-map/lib/util/bboxFeature.js
src/lib/components/molecules/canvas-map/lib/util/bounds.js
src/lib/components/molecules/canvas-map/lib/util/coordinate.js
src/lib/components/molecules/canvas-map/lib/util/extent.js
src/lib/components/molecules/canvas-map/lib/util/index.js
src/lib/components/molecules/canvas-map/map.stories.jsx
src/lib/shared/hooks/useTouchOrHover.js

The reason that hit detection broke for preprojected maps is that in various place in the Map component I implicitly made the assumption that map coordinates would always represent geographical coordinates (WGS84). This assumption obviously doesn't hold up when our map data has already been projected into screen coordinates.
The way I started untangling that mess is by making explicit types for different sets of coordinates, i.e. `Extent` vs `GeoBounds` and adding JSDoc types where relevant. This work is not entirely finished, but so far it seems to point to a direction where we can mostly express those values as `[x,y]` coordinates and `{minX, maxX, minY, maxY}` extents. We may  ultimately want to make it so that geographic coordinates `[lng, lat]` and bounds `{southWest, northEast}` are …

Fix hit detection for preprojected maps

---

src/lib/components/molecules/canvas-map/Map.jsx

Using a custom prop name (`mapRef`) vs `ref` seems to solve this problem.
I guess Preact is keen to set `ref` itself, as it is a "special" prop name? And really, we shouldn't be overriding `ref` and have it point to something that isn't an element reference.

Fix map component ref

---

src/lib/components/molecules/canvas-map/lib/Map.js
src/lib/components/molecules/canvas-map/lib/View.js
src/lib/components/molecules/canvas-map/lib/util/extent.js
src/lib/components/molecules/canvas-map/map.stories.jsx

This PR fixes a small bug in the `View` class' `boundsForExtent` method, which assumes its `extent` parameter is a 4-tuple 
(which it presumably was until f787b36742ef6862cba16ed7f40d165b97cb872e), when it's actually an `Extent` instance.
At least, this is what I've observed when using the Map component (see the screenshots below) - please let me know if there's a chance that this `extent` parameter could be an `Extent` _or_ a 4-tuple.

Use Extent's new minX, minY, etc. properties in View.boundsForExtent

---

src/lib/components/molecules/canvas-map/lib/geometry/Point.js

Looks like we forgot to update this Point class along with the others in the recent preprojected geography fixes (c07c124), in which we changed from expressing _extents_ as 4-length arrays (e.g. `[2,4,7,2]`) to a proper `Extent` class, which internally expresses them as `{ minX: 2, minY: 4, maxX: 7, maxY: 2 }`.
This fixes the missing text issue in the canvas map stories...

Use new Extent class in Point

---

jsconfig.lib.json
package.json
pnpm-lock.yaml
src/lib/shared/helpers/labelsUtil.js
vite.config.js

This PR makes a number of changes to our build process, with the aim of improving the experience for library consumers.
Rather than bundling every source file into a single `index.js` output, this PR changes our build config to keep the directory structure that we have in `src/lib`.
For our component library, considering it'll only ever be consumed by the interactives and perhaps neighbouring teams using our atom template, bundling isn't really necessary, and it comes at the cost of relying more on flaky sourcemaps.
This change was motivated by struggling with troubleshooting components in the US elections project: our stack traces aren't pointing to the correct places in source code. Where possible, not relying on source maps and having our library output resemble source files as closely …

Export types, remove CJS exports, don't bundle files

---

src/lib/styles/foundation/usPartyColors.scss

New and amended colors coming from here: 
https://www.figma.com/design/RZHnmwc2tmB6j1k4bNtyND/Style-guide-colour-original?node-id=0-1&t=hamHGA9YsrrgijOw-1
Party codes coming from here: 
https://developer.ap.org/ap-elections-api/docs/index.html#t=Party_Codes.htm 
In the naming I've stuck to AP's three-letter party codes, except for Kennedy who doesn't have a party so will come up as "ind" and for the Independent Democrats who will also come up as "ind". 
have assigned these: 
Kennedy - `ken`
Independent Democrat - `ind-dem`
NB: Independent Democrats - will come up as "ind" plus a "caucusWith" property. And to identify Robert Kennedy I presume we need to use his candidate name. We'll have to identify them at some point in our data pipeline

US party colors: add new + tweak

---

src/lib/components/particles/circle-icon/index.jsx

Tiny fix to the `CircleIcon` component that'll let us use its `styles` prop properly (🥁).
I've checked for usages of this styles.svg property across our codebases and this won't break anything - it isn't used anywhere!

Fix CircleIcon styles prop

---

src/lib/components/molecules/canvas-map/lib/renderers/MapRenderer.js
src/lib/components/molecules/canvas-map/lib/renderers/TextLayerRenderer.js
src/lib/components/molecules/option-picker/style.module.css

This PR fixes an issue with the canvas map's `TextLayer` component, that appears when trying to set the `declutter` prop to false.
It also tweaks the option picker to make its appearance a bit more predictable and balanced.
This change makes sure to null check `declutterTree` in `TextLayerRenderer`, which will be null when creating a `TextLayer` with declutter=false. Without this, the map just crashes when this prop is set to false.
It also makes sure to draw declutter=true and declutter=false layers in order, rather than "all declutter=false first, then all declutter=true".
This fix removes the maximum item width, so the items fill the container regardless of its size. It also ensures that, by default, items are evenly-sized in the container.
| Before | After |
| - | - |
| <img …

Fix TextLayer decluttering, fix OptionPicker item sizing

---

src/lib/components/organisms/ticker/style.module.scss

The overlay gradient was blocking scroll events at the right-hand end of the ticker. 
This stops the gradient div capturing pointer events so that the whole ticker bar is scrollable 
fixed:
https://github.com/user-attachments/assets/33234d99-e0b4-435f-924d-7ab35534a8d7

Ticker CSS tweak: allow horiz scroll even behind gradient

---

src/lib/components/molecules/canvas-map/lib/renderers/FeatureRenderer.js
src/lib/components/molecules/canvas-map/lib/styles/Style.js
src/lib/components/particles/relative-time-sentence/index.jsx

This PR adds a `pointRadius` property to the `Style` class, that lets us control the radius of the "Point"-type geometries,
drawn by the underlying d3-geo drawing functions.
This uses [the pointRadius function exposed by d3's path generator](https://d3js.org/d3-geo/path#path_pointRadius).
Now, when drawing "Point"-type map features, we can use a `Style` instance like so...
```js
return new Style({
pointRadius: 50,
fill: new Fill({
color: "#ff0000"
}),
})
```

Add 'pointRadius' to 'Style' class

---

src/lib/components/molecules/canvas-map/context/MapContext.jsx
src/lib/components/molecules/canvas-map/lib/layers/TextLayer.js
src/lib/components/molecules/canvas-map/lib/layers/VectorLayer.js

This change fixes a subtle bug in the code that synchronises our React component hierarchy (of VectorLayer and TextLayer components) with the layers that are rendered on the map.
It also adds some debug code to this function, to help with future troubleshooting.

Fix canvas map component hierarchy sync

---

src/lib/components/organisms/ticker/index.jsx

This component wasn't accepting the style property, which meant it could not be styled by the client repo. 
Adding in - as per other components eg: https://github.com/guardian/interactive-component-library/blob/main/src/lib/components/particles/stacked-bar/index.jsx#L31

Ticker: allow style as a property

---

src/lib/components/molecules/canvas-map/lib/Feature.js
src/lib/components/molecules/canvas-map/lib/layers/TextLayer.js
src/lib/components/molecules/canvas-map/lib/layers/VectorLayer.js
src/lib/components/molecules/canvas-map/lib/renderers/FeatureRenderer.js
src/lib/components/molecules/canvas-map/lib/renderers/MapRenderer.js
src/lib/components/molecules/canvas-map/lib/renderers/TextLayerRenderer.js
src/lib/components/molecules/canvas-map/lib/renderers/VectorLayerRenderer.js
src/lib/components/molecules/canvas-map/lib/sources/VectorSource.js
src/lib/components/molecules/canvas-map/lib/styles/Style.js
src/lib/components/molecules/canvas-map/lib/styles/Text.js
src/lib/components/molecules/canvas-map/map.stories.jsx

This PR adds new _callout_ and _icon_ features to the `TextLayer` component, which lets us draw map labels that look like this.
Both of these features are made available through the `Text` class, provided to `Style`.
`callout`'s main property is `offsetBy`, which lets you declare how far away you'd like the label to be placed. There are other properties that allow you to customise padding, leader line width and colour.
`icon` provides a bunch of properties to customise a canvas-drawn circle (other shapes will need to be implemented). Crucially, its `style` property accepts a `Style` instance, meaning you can re-use existing logic for styling map features.
```jsx
return new Style({
stroke: null,
text: new Text({
anchor: "left",
content: feature.properties.text,
callout: {
offsetBy: { x: …
```

Add callouts and icons to `TextLayer`

---

src/lib/components/molecules/result-summary/index.jsx
src/lib/components/molecules/result-summary/result-summary.stories.jsx
src/lib/components/molecules/result-summary/style.module.css

Pushing the datestamp onto the same line as the title of the card required much more rebuilding than I would like but 🤷‍♀️ 
I could no longer use the <ControlChange> component because its structure didn't give enough styling flexibility so have pasted it with a few adjustments in the <ResultsSummary>
New property `isSlim` controls if you see this or the default 
Datestamp span can be optionally bumped onto the next line with CSS injected from the client

Results card: create slim version

---

src/lib/components/molecules/result-summary/index.jsx

So that ticker cards can be clicked on to select a new result, this ResultsSummary component needs an onClick event to be passed thru

Results Summary: add onClick event

---

src/lib/components/molecules/svg-map/index.jsx

Export saveSVG helper so that it can be used by client.

Export saveSVG helper

---

src/lib/components/molecules/canvas-map/lib/renderers/TextLayerRenderer.js
src/lib/components/molecules/canvas-map/lib/styles/Text.js
src/lib/components/molecules/canvas-map/map.stories.jsx

This PR changes the `Text` class to offer an `offsetTo` vs `offsetBy`, in its callout options.
This change lets us more precisely and predictably place callout labels. It's now much easier to align multiple callouts: providing the same X or Y coordinate means two or more callouts will be aligned.
This comes at the cost of ease of use: now, consumers will have to know the coordinates of their desired callout placement, which likely means looking at the input geography files.

Offer `offsetTo` instead of `offsetBy` in `TextLayer`

---

src/lib/components/molecules/canvas-map/lib/layers/TextLayer.js
src/lib/components/molecules/canvas-map/lib/renderers/TextLayerRenderer.js

`mouseover` and `mouseout` are fired by pointing devices (mice) _and_ touch screens. A `mouseover` is fired even a _mouse_ moves, and when a touch screen is _tapped_.
Really, _hovering_ is only something that happens with a mouse.
This changes makes it so that `TextLayer`'s `onHover` and `restyleOnHover` props are only triggered in response to mouse events.

Use pointerover/pointerout vs mouseover/mouseout in TextLayer logic

---

src/lib/components/molecules/canvas-map/lib/Map.js
src/lib/components/molecules/canvas-map/lib/View.js
src/lib/components/molecules/canvas-map/lib/layers/VectorLayer.js
src/lib/components/molecules/canvas-map/lib/renderers/MapRenderer.js
src/lib/components/molecules/canvas-map/lib/renderers/TextLayerRenderer.js
src/lib/components/molecules/canvas-map/lib/renderers/VectorLayerRenderer.js
src/lib/components/molecules/option-picker/index.jsx

Adds `renderToCanvas` method to `Map.js`, to enable rendering maps to static image files.

Render map to canvas (for PNG export)

---

src/lib/components/molecules/canvas-map/lib/renderers/FeatureRenderer.js

It seems d3-geo will default to a fixed size when we ask it to draw points with `pointRadius: 0`, leading to situations like this: all of these points are meant to be 0 radius!
This PR simply skips drawing altogether for features whose `pointRadius` is 0.

Don't draw features with `pointRadius: 0`

---

src/lib/components/molecules/canvas-map/lib/Map.js
src/lib/components/molecules/canvas-map/lib/layers/TextLayer.js
src/lib/components/molecules/canvas-map/lib/renderers/VectorLayerRenderer.js
src/lib/components/molecules/canvas-map/lib/util/toRgba.js

Fixes bug in VectorLayerRenderer, where the canvas is returned as a new element to be added to the map if `opacity===0`. `renderFrame` should return `null` unless a new DOM element has been created.
Also includes small stylistic tweaks and improvement of JSDoc types.

Fix bug in VectorLayerRenderer

---

src/lib/components/molecules/canvas-map/lib/renderers/MapRenderer.js

This change replicates the behaviour we had prior to f2030d2, before I removed it!
It fixes the glitchy zooming and panning issues we've been noticing in the US election pages recently.
Without this fix, we're creating a new canvas element whenever anything in the map changes, including changing zoom level or pan position. Creating a new canvas for every frame means we're destroying and re-attaching the mouse/touchmove listeners added by d3-zoom to control zooming and panning, leading to the stuttery behaviour we've been noticing.
Using a single canvas element, as we used to, solves this problem.
| Before | After |
| - | - |
| <video src="https://github.com/user-attachments/assets/3ea45ae2-820a-4526-9be3-1de960d867b7"> | <video src="https://github.com/user-attachments/assets/b4c44eea-1e53- …

Re-use canvas between renders

---

src/lib/components/molecules/canvas-map/lib/Map.js

In some niche cases where a VectorLayer is rendered without any features, `layerExtent` is null here.

Null check layerExtent in map's findLayers

---

src/lib/components/molecules/canvas-map/lib/Map.js

This fix ensures that the Map component's `inModalState` prop works correctly, which is designed to allow the map to be panned with a single finger, instead of two.
Currently, the line of code that this PR touches means that one-finger gestures are _always_ filtered, regardless of the value of the `_collaborativeGesturesEnabled` flag.
This PR makes sure that we _call_ the function that returns this value, rather than checking a reference to the function itself, which will always be truthy!

Fix canvas map "collaborativeGesturesEnabled" check, one-touch panning

---

src/lib/components/molecules/refresh-indicator/style.module.scss

Using align-items: stretch sees the text and circle icon offset in some layout situations. Using center means they'll always be aligned.

Center align refresh indicator circle icon

---

.github/workflows/pr-npm-comment.yml
.storybook/main.js

This tab only shows the story args object for some reason, not a full component snippet as advertised. While this info is perhaps useful, it's mainly confusing, especially for those who don't know the internals of our Storybook.
For this reason, it's better to hide this tab, for now.

Hide 'Code' tab

---

src/lib/components/molecules/page-section/index.jsx
src/lib/components/molecules/page-section/style.module.scss
src/lib/components/organisms/index.js
src/lib/components/organisms/ticker-v2/Gradient.jsx
src/lib/components/organisms/ticker-v2/index.jsx
src/lib/components/organisms/ticker-v2/stories.module.scss
src/lib/components/organisms/ticker-v2/style.module.scss
src/lib/components/organisms/ticker-v2/ticker.stories.jsx

This new Ticker2 component aims to simplify the original ticker component by relying on more native functionality.
It uses `scrollTo` instead of `translateX`, and `display: flex` to lay out the elements. It also allows items to be variable width.

Add initial Ticker v2 component; allow no "header" in PageSection
