guardian/interactive-component-library

.storybook/main.ts
.storybook/vite.config.ts
package.json
pnpm-lock.yaml

Update project dependencies and config to use Preact instead of React

Switch from React to Preact

---

src/lib/components/organisms/coalitions-tracker/coalitions-tracker.stories.jsx
src/lib/components/organisms/coalitions-tracker/index.jsx
src/lib/components/organisms/coalitions-tracker/style.module.scss
src/lib/components/organisms/index.js
src/lib/components/particles/stacked-bar/index.jsx
src/lib/shared/hooks/useWindowSize.js

This does all it's supposed to do now but still has a line that randomly assigns the list member colour. I'll change this once we know what to do with styling

Coalitions

---

src/lib/components/molecules/tooltip/tooltip.stories.jsx
src/lib/components/molecules/tooltip/useMousePosition.js

* Adds a story to explain overflow behaviour of the tooltip.
* Fixes an issue where the reported mouse position was incorrect

Tooltip improvements

---

src/lib/components/particles/square-cut-corner-icon/index.jsx
src/lib/components/particles/square-cut-corner-icon/style.module.scss
src/lib/components/particles/stacked-grid/style.module.css

Small cleanup card: 
* Square Corner Cut icon - dark mode /

Stacked grid + icon cleanups: small changes 

---

src/lib/components/molecules/topline-result/index.jsx
src/lib/components/molecules/topline-result/style.module.scss
src/lib/components/molecules/topline-result/topline-result.stories.jsx

adds candidate variant to topline result component

---

.storybook/preview.js
src/lib/components/molecules/page-section/index.jsx
src/lib/components/molecules/page-section/page-section.stories.jsx
src/lib/components/molecules/page-section/stories.module.scss
src/lib/components/molecules/page-section/style.module.scss

Adds a backgroundColor prop to PageSection component.

Page section bg

---

src/lib/components/molecules/column-chart/columnchart.stories.jsx
src/lib/components/molecules/column-chart/index.jsx

adds bottom margin if all values in columnChart are positive

---

src/lib/components/molecules/map/context/SVGMapProvider.jsx
src/lib/components/molecules/map/helpers/geoMath.js
src/lib/components/molecules/map/index.jsx
src/lib/components/molecules/map/layers/Point.jsx
src/lib/components/molecules/map/layers/Polygon.jsx
src/lib/components/molecules/map/map.stories.jsx
src/lib/components/molecules/map/renderers/SVGRenderer.jsx
src/lib/components/molecules/tooltip/index.jsx
src/lib/components/molecules/tooltip/useTooltipTarget.js

* Some bug fixes
* Layer-based `findFeatureAtPoint`

Tooltip component changes

---

src/lib/components/molecules/control-change/index.jsx
src/lib/components/organisms/ticker/index.jsx
src/lib/components/organisms/ticker/style.module.scss
src/lib/components/particles/stacked-bar/index.jsx

Tweaks to a number of components based on design feedback

Design tweaks

---

.storybook/preview.scss
src/lib/components/molecules/search-input/style.module.css
src/lib/components/molecules/table/index.jsx
src/lib/components/molecules/table/style.module.scss
src/lib/components/molecules/topline-result/index.jsx
src/lib/components/molecules/topline-result/style.module.scss
src/lib/components/molecules/topline-result/topline-result.stories.jsx
src/lib/components/organisms/ticker/index.jsx
src/lib/components/organisms/ticker/style.module.scss
src/lib/components/particles/button/style.module.css
src/lib/components/particles/chevron/index.jsx
src/lib/components/particles/chevron/style.module.css
src/lib/components/particles/close-button/style.module.css
src/lib/components/particles/info-button/style.module.css
src/lib/components/particles/stacked-grid/index.jsx
src/lib/components/particles/stacked-grid/style.module.css
src/lib/styles/generated/font-sizes.css
src/lib/styles/main.scss

Fixes some styling issues related to the app.

App changes

---

.storybook/preview.scss
package.json
pnpm-lock.yaml
src/lib/components/molecules/table/docs.mdx
src/lib/components/molecules/table/table.stories.jsx

Add column definitions to Table docs in Storybook

---

.github/workflows/ci.yml
src/lib/components/molecules/map/hooks/useZoom.js
src/lib/components/molecules/map/map.stories.jsx
src/lib/components/molecules/map/renderers/CanvasRenderer.jsx
src/lib/components/particles/change-bar/index.jsx
src/lib/shared/helpers/createStore.js

Add CI workflow for Github Actions

Add CI workflow

---

src/lib/components/molecules/refresh-indicator/index.jsx
src/lib/components/molecules/refresh-indicator/style.module.scss

Fix refresh indicator

---

src/lib/styles/foundation/euPartyColors.scss

Adding new colors for EU elections such as Others and Undeclared

---

src/lib/styles/foundation/partyColors.scss

Makes these names more consistent with the abbreviations we get from PA

UK party colors rename

---

src/lib/components/molecules/dropdown/dropdown.stories.jsx
src/lib/components/molecules/dropdown/index.jsx
src/lib/components/molecules/dropdown/style.module.css

* Fixes z-index issue
* Fixes checkmark overlapping with title in some cases

Dropdown fixes

---

src/lib/styles/foundation/euPartyColors.scss

Adds declared color to the palette

---

src/lib/components/molecules/dropdown/dropdown.stories.jsx
src/lib/components/molecules/dropdown/index.jsx
src/lib/components/molecules/dropdown/style.module.css

Adds subheaders for grouping in the dropdown menu

---

src/lib/components/molecules/party-profile/index.jsx
src/lib/components/molecules/party-profile/party-profile.stories.jsx

Adds an alt text attribute to image in the Party Profile Card

Party profile pics: add alt text to photo

---

src/lib/components/molecules/page-section/style.module.scss
src/lib/components/molecules/party-profile/style.module.css

* Fix missing section headers in iPad app
* Remove fixed widths from party profile cards

Ipad fixes

---

src/lib/components/molecules/dropdown/dropdown.stories.jsx
src/lib/components/molecules/dropdown/index.jsx
src/lib/components/molecules/dropdown/style.module.css

Example use case for the UK general elex:

Support multiple select on Dropdown menu

---

src/lib/components/particles/stacked-bar/index.jsx

adding a comment, removing another comment. Should have been added to previous pr 
https://github.com/guardian/interactive-component-library/pull/138

Stacked Bar: small cleanup of previous pr 

---

src/lib/components/molecules/canvas-map/Map.jsx
src/lib/components/molecules/canvas-map/lib/Map.js
src/lib/components/molecules/canvas-map/lib/renderers/FeatureRenderer.js
src/lib/components/molecules/canvas-map/lib/renderers/MapRenderer.js
src/lib/components/molecules/canvas-map/lib/renderers/VectorLayerRenderer.js
src/lib/components/molecules/canvas-map/style.module.scss
src/lib/components/molecules/modal/index.jsx
src/lib/components/molecules/modal/style.module.css
src/lib/styles/foundation/colors.scss

See commit messages for more detailed description.

Improvements related to MapSection for UK general elex

---

src/lib/components/molecules/slope-chart/index.jsx
src/lib/components/molecules/slope-chart/slopechart.stories.jsx
src/lib/components/particles/waffle/index.jsx
src/lib/components/particles/waffle/waffle.stories.jsx

add svg ids to some components to make them easier to crowbar

---

src/lib/components/molecules/search-input/style.module.css
src/lib/components/particles/close-button/index.jsx
src/lib/components/particles/close-button/style.module.css

Fix for this issue: https://trello.com/c/xEBRQ6DN/474-app-map-overlay-cards-x-isnt-in-center-of-cirlce

Fix app issue with close button

---

src/lib/components/molecules/control-change/index.jsx
src/lib/components/particles/gradient-icon/gradientStore.js
src/lib/components/particles/gradient-icon/index.jsx

Fix for: https://trello.com/c/bH2XjHT8/494-random-control-change-icons-not-showing-in-map-cards-component-library-issue

Simplify GradientIcon to resolve bugs

---

src/lib/components/molecules/table/table.stories.jsx
src/lib/components/molecules/table/useTable.jsx

Change sort descending and ascending functions to deal with null values and place them at the end and beginning of sorts to fix order issues in the uk general election results table
Fix an issue with null values causing component to fail

Sorting fix

---

src/lib/components/molecules/page-section/style.module.scss
src/lib/components/molecules/table/index.jsx
src/lib/components/molecules/table/style.module.scss

Sticky headers and PageSection top border fix

---

src/lib/components/molecules/page-section/index.jsx
src/lib/components/molecules/page-section/style.module.scss

Because of changes to DCR page rendering, the `PageSection` component needed some tweaks.

Page section style tweaks

---

src/lib/components/molecules/canvas-map/Map.jsx
src/lib/components/molecules/canvas-map/lib/Map.js
src/lib/components/molecules/canvas-map/lib/interpolators/interpolateStyles.js
src/lib/components/molecules/canvas-map/lib/renderers/FeatureRenderer.js
src/lib/components/molecules/canvas-map/lib/styles/Fill.js
src/lib/components/molecules/canvas-map/lib/styles/Stroke.js
src/lib/components/molecules/canvas-map/lib/util/toRgba.js
src/lib/components/molecules/modal/index.jsx
src/lib/components/molecules/search-input/index.jsx

* [Allow modal styles to be overridden](https://github.com/guardian/interactive-component-library/commit/ca49f34fa41511406bd8f1d74ec8d37808e4e2a3)
* [Allow for stroke and fill opacity](https://github.com/guardian/interactive-component-library/commit/0bc1eb4429fd0a5f68d271b72c150792d03debd7)
* [Draw with rgba colours to allow for layer AND feature opacity](https://github.com/guardian/interactive-component-library/commit/e107389027ee2eaa4f42011ae9f781ec0e15125d)
* [Enable collaborative gestures only when not in modal state](https://github.com/guardian/interactive-component-library/commit/f4740d04eb9e35a74f84e1db83166c0df3af33d1)
* [Search input onFocus callback](https://github.com/guardian/interactive-component-library/commit/d442fef630e1b03d60531512ba40f846be67b4c3)

Small tweaks to map-related components

---

src/lib/components/molecules/canvas-map/lib/Map.js
src/lib/components/molecules/canvas-map/lib/View.js
src/lib/components/molecules/canvas-map/lib/renderers/TextLayerRenderer.js
src/lib/components/molecules/canvas-map/lib/util/distance.js
src/lib/components/molecules/canvas-map/lib/util/resolution.js
src/lib/components/molecules/canvas-map/lib/util/zoomLevel.js

Fix for: https://trello.com/c/SGQ4uOCD/540-fix-label-overlap

Fix label overlap and implement zoom levels for consistency between breakpoints

---

src/lib/components/particles/stacked-bar/style.module.css

default label fill for stacked bars

---

src/lib/shared/helpers/labelsUtil.js
src/lib/shared/helpers/labelsUtils.test.js
src/lib/shared/helpers/shouldUpdate.js

Add basic types and tests to the label utils
`pnpm test`
Improve IDE autocompletion
If the team maintaining this code is unfamiliar with types, it could could be unmaintainable.

Add types & tests to labels utils

---

src/lib/components/molecules/canvas-map/lib/layers/TextLayer.js
src/lib/components/molecules/canvas-map/lib/renderers/TextLayerRenderer.js
src/lib/components/molecules/canvas-map/lib/styles/Style.js

This PR adds a number of props to the `TextLayer` component that lets us respond to click and hover events on them.
With `VectorLayer`, the typical solution involves adding a click handler on a container div for the entire map, then using `map.findFeatures(clickCoordinates)` to find the features that were clicked on. This approach doesn't suit `TextLayer` however, as they're not drawn to the canvas, they're rendered in the DOM.
For this reason, it makes much more sense to just add a click listener to the DOM elements themselves.
The `onClick` prop is as you'd expect. Pass a callback to it that accepts a `feature` argument, and it'll be called whenever any feature in the `TextLayer` is clicked on.
```jsx
<TextLayer.Component
onClick={(feature) => selectStateById(feature.id)}/>
```
The …

Add `onClick`, `onHover`, `restyleOnHover` to `TextLayer`
